In [68]:
import numpy as np


In [69]:
a = np.array([[12,34,56],[45,78,14]])
type(a)  #Shows variable Data Type
a.dtype # Shows store values Data type
a.shape  # shows the shape of array like(2,3)
a.size # Shows the count of element in array
a.ndim # Shows the number of dimensions



2

In [70]:
a = np.array([12,34,56,45,78,14])
a.strides # Shows the number of bytes to step in each dimension when traversing an array


(8,)

In [71]:
a = np.array([[12,34,56,14],[45,78,14,12],[32,72,19,34]])
print(a)
a.shape


[[12 34 56 14]
 [45 78 14 12]
 [32 72 19 34]]


(3, 4)

In [72]:
a = np.array([[12,34,24,14],
             [45,67,86,21],
             [78,45,32,54],
             [45,37,39,67],
             [89,65,87,56]])

print(a)

[[12 34 24 14]
 [45 67 86 21]
 [78 45 32 54]
 [45 37 39 67]
 [89 65 87 56]]


In [73]:
data = {
    "Total": np.sum(a, axis = 1),
    "avg" : np.average(a, axis = 1),
    "Max" : np.max(a, axis = 1)
    
 }
data

{'Total': array([ 84, 219, 209, 188, 297]),
 'avg': array([21.  , 54.75, 52.25, 47.  , 74.25]),
 'Max': array([34, 86, 78, 67, 89])}

In [74]:
a = np.array([[12,34,24,14],
             [45,67,86,21],
             [78,45,32,54],
             [45,37,39,67]])

In [75]:
a.reshape(-1,2)

array([[12, 34],
       [24, 14],
       [45, 67],
       [86, 21],
       [78, 45],
       [32, 54],
       [45, 37],
       [39, 67]])

In [76]:
a.flatten() # flatten the array to 1D array  (change the original array)

array([12, 34, 24, 14, 45, 67, 86, 21, 78, 45, 32, 54, 45, 37, 39, 67])

In [77]:
a.ravel() # return a flatten array. It return a view of the original array whenever possible. (copy of original)
# it faster then flatten() 

array([12, 34, 24, 14, 45, 67, 86, 21, 78, 45, 32, 54, 45, 37, 39, 67])

In [78]:
# a.ravel? #To find the properties of variable or function, use ?

In [79]:
a = np.array([[23,43,23],
              [23,43,54]])
a.shape
np.sum(a, axis = 1)

array([ 89, 120])

In [80]:
a = np.array([[[23,24,32],
              [45,21,43],
              [65,34,65]]])
a.ndim
a.shape

(1, 3, 3)

In [81]:
a.reshape(-1, 3) # converting 3D to 2D

array([[23, 24, 32],
       [45, 21, 43],
       [65, 34, 65]])

In [82]:
# # question
# 1 - > create a 3d array having 9 elements
# 2 - > create 2d array having 32 elements
# 3 - > reshape the above array in two diff shapes
# 4 - > find the transpose of each array

In [83]:
a = np.array([[[2,3,4],[5,6,7],[7,8,9]]])
a.size

9

In [84]:
import numpy as np
a = np.array([[2,3,4,5],[2,4,5,6],[7,9,5,8],[9,4,6,7],[7,7,5,8],[7,7,5,8],[7,7,5,8],[7,7,5,8]])
a.size
a.ndim

2

In [85]:
a.reshape(-1,8)
a.reshape(2, 16)

array([[2, 3, 4, 5, 2, 4, 5, 6, 7, 9, 5, 8, 9, 4, 6, 7],
       [7, 7, 5, 8, 7, 7, 5, 8, 7, 7, 5, 8, 7, 7, 5, 8]])

In [86]:
a.transpose()

array([[2, 2, 7, 9, 7, 7, 7, 7],
       [3, 4, 9, 4, 7, 7, 7, 7],
       [4, 5, 5, 6, 5, 5, 5, 5],
       [5, 6, 8, 7, 8, 8, 8, 8]])