In [2]:
import numpy as np


In [3]:
# write an example of masking

In [4]:
k = np.array([100, 56, 87, 56, 65, 78, 89, 76, 98, 45, 57, 87])

In [5]:
mask = k>72
print(mask) # simple true false ans will give because of > condition
print(k[mask]) # only biggner value give when "k" will write

[ True False  True False False  True  True  True  True False False  True]
[100  87  78  89  76  98  87]


In [6]:
k = np.array([100, 56, 87, 56, 65, 78, 89, 76, 98, 45, 57, 87])


In [7]:
mask = (k>70) & (k<90)
print(k[~mask]) # gives  the values which is not in the range of 70 & 90 using ~

[100  56  56  65  98  45  57]


In [8]:
cond = [(k>=50) & (k<70), ((k>=70) & (k<=100))]
choice = ["small", "medium"]
print(np.select(cond, choice, default = "Big")) # select function is used to select the values based on the condition and choice. If the condition is true it will return the corresponding choice value otherwise it will return the defult value

['medium' 'small' 'medium' 'small' 'small' 'medium' 'medium' 'medium'
 'medium' 'Big' 'small' 'medium']


In [13]:
arr = np.array([12, 43, 56, 87, 98, 46, 78, 98, 67, 78])
print(np.where(arr%2 == 0)) # where functon is used to select the values based on the condition and choice. It return the index of the value of the elements that satisfy the condition

(array([0, 2, 4, 5, 6, 7, 9]),)


In [ ]:
print(np.where(arr%2 == 0, arr, 0)) # arr shows even number value and 0  shows which does not support the condition 

In [10]:
print(np.where(arr%3 == 0, arr, 0).mean())

25.5


In [14]:
con = [(arr>=10)&(arr<50), (arr>=50) & (arr<85)]
choice = "small", "medium"
print

<function print(*args, sep=' ', end='\n', file=None, flush=False)>